### ISSUE TITLE
Upgrade to Laravel 5.4

### ISSUE THREAD

**Issue by computerfr33k** [pulkitjalan/google-apiclient#18]
```php
[2017-01-27 19:34:45] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Illuminate\Foundation\Application::share() in vendor/pulkitjalan/google-apiclient/src/GoogleServiceProvider.php:39
Stack trace:
#0 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(568): PulkitJalan\Google\GoogleServiceProvider->register()
#1 vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(74): Illuminate\Foundation\Application->register(Object(PulkitJalan\Google\GoogleServiceProvider))
#2 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(543): Illuminate\Foundation\ProviderRepository->load(Array)
#3 vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()
#4 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(208): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#5 vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(270): Illuminate\Foundation\Application->bootstrapWith(Array)
#6 vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(115): Illuminate\Foundation\Console\Kernel->bootstrap()
#7 artisan(34): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 {main}  
```

**Comment by pulkitjalan** [comment]
Thanks, I'll have a fix for this over the weekend

**Comment by computerfr33k** [comment]
Awesome, Thanks!
